### PR TITLE
Fix Cookie#domain Warnings

### PR DESCRIPTION
**Pull request by mattpickle**

### CODE REVIEW

**Comment by mattpickle** [comment]
Warnings: https://circleci.com/gh/doximity/doximity_features/1238
screen shot 2015-10-05 at 11 40 11 am

**Comment by mattpickle** [comment]
No warnings:  https://circleci.com/gh/doximity/doximity_features/1239

**Comment by mattpickle** [comment]
@divoxx CR?

**Comment by divoxx** [comment]
:+1: no-QA

**Pull request merged**
